### PR TITLE
added chair List and Carl von Linde Kurse

### PR DESCRIPTION
**Pull request by jfr2102**
- [x] I made sure that the arrays in `routes.php` are still alphabetically sorted. :sparkles:

### CODE REVIEW

**Review by joschahenningsen — CHANGES_REQUESTED** [review]
Thanks for contributing! Can you double check the order of the routes please? :)

**Comment by jfr2102** [comment]
> 
> 
> Thanks for contributing! Can you double check the order of the routes please? :)

Sorry! I think i changed the 2 entries messing it up now. Can i retrigger CI flow myself by the way?

**Comment by joschahenningsen** [comment]
No worries!

> Can i retrigger CI flow myself by the way?

This is your first contribution, all future workflows will run automatically :)

**Review by joschahenningsen — APPROVED** [review]
:tada:

**Pull request merged**
