### PR TITLE
Update GitHub actions

### PR DESCRIPTION
**Pull request by Garfield96**
This PR adds GitHub actions to Dependabot. In addition, `docker/build-push-action` was updated to v2, which splits the functionality of v1 into multiple actions. I tried to translate the functionality of v1 to v2 following the upgrade guide [https://github.com/docker/build-push-action/blob/master/UPGRADE.md](https://github.com/docker/build-push-action/blob/master/UPGRADE.md). However, I cannot test these changes.

### CODE REVIEW

**Comment by joschahenningsen** [comment]
@kordianbruck All I can do here is merge and hope for lighthouse to do its best :D But looks good to me

**Review by joschahenningsen — APPROVED** [review]

**Comment by joschahenningsen** [comment]
Let's just see what happens :D Thx!

**Comment by Garfield96** [comment]
@joschahenningsen It probably fails because the Docker registry `docker.pkg.github.com` is outdated. See [https://github.com/docker/buildx/issues/780](https://github.com/docker/buildx/issues/780). Replacing it with `ghcr.io` should solve this issue.

**Comment by joschahenningsen** [comment]
Good catch, can you create a follow-up? @Garfield96 
I'll have a chat with Kordian about possible changes that need to be done to the server.

**Comment by Garfield96** [comment]
I'll create a follow-up in a few minutes.

**Pull request merged**
