### PR TITLE
Added Links to 'Semesterticket' and 'Referat für Mobilität'

### PR DESCRIPTION
**Pull request by kb-master**
- [x] I made sure that the arrays in `routes.php` are still alphabetically sorted. :sparkles:

### CODE REVIEW

**Comment by joschahenningsen** [comment]
Are there any exciting news about the Semesterticket? Will the 365 day ticket be available for students?

**Review by joschahenningsen — APPROVED** [review]

**Comment by kb-master** [comment]
> Are there any exciting news about the Semesterticket? Will the 365 day ticket be available for students?

Thanks for approval. 
Unfortunately not yet. But we are in negotiations with the MVV, the City of Munich and the Bavarian Government to make it available as soon as possible. 

For more informations please check mobilitaet.tum.sexy in a few days or write us at mobilitaet@fs.tum.de :)

**Comment by joschahenningsen** [comment]
Awesome, looking forward to it!

**Comment by kb-master** [comment]
> (Was just about to merge this, any reason you closed it? :D)

...by mistake ;)

**Pull request merged**
