### PR TITLE
Updated GRNVS redirect

### PR DESCRIPTION
**Pull request by jonas-de**
- [x] I made sure that the arrays in `routes.php` are still alphabetically sorted. :sparkles:

### CODE REVIEW

**Review by joschahenningsen — APPROVED** [review]
This seems to be a redirect from grnvs.net. Wouldn't it be a safer bet to go for that domain in case they change the target?

**Comment by jonas-de** [comment]
I just thought it'd be nice to save that redirect and just update the link here in the unlikely case they change it.

**Comment by joschahenningsen** [comment]
Sounds good to me :)

**Comment by joschahenningsen** [comment]
grnvs.net doesn't seem to redirect anymore :D

**Pull request merged**
